export interface OnlineDrugItem {
  barcode: string;
  name: string;
  nameEn: string;
  scientificName: string;
  category: string;
  form: string;
  strength: string;
  manufacturer: string;
  country: string;
  stripsPerPackage: number;
  piecesPerStrip: number;
  requiresPrescription: boolean;
  locationRack: string;
  standardCost: number;
  standardPrice: number;
  indications?: string;
}

export const ONLINE_DRUG_CATEGORIES = [
  'الكل',
  'مضادات حيوية وميكروبية',
  'مسكنات ومضادات التهاب',
  'أدوية الضغط والقلب والأوعية',
  'أدوية السكري والغدد',
  'أدوية الجهاز الهضمي والمعدة',
  'أدوية الجهاز التنفسي والبرد والحساسية',
  'أدوية الأعصاب والنفسية والصداع',
  'الفيتامينات والمكملات الغذائية والمعادن',
  'أدوية العيون والأنف والأذن',
  'أدوية الجلدية والمطهرات والمراهم',
  'أدوية المسالك والنساء والولادة',
  'المحاليل الوريدية وأدوية الطوارئ'
] as const;

export const ONLINE_DRUG_MANUFACTURERS = [
  'الكل',
  'GSK / جلاكسو سميث كلاين',
  'Sanofi / سانوفي',
  'Pfizer / فايزر',
  'Novartis / نوفارتس',
  'AstraZeneca / أسترازينيكا',
  'Bayer / باير',
  'Abbott / أبوت',
  'Roche / روش',
  'Merck / ميرك',
  'Boehringer Ingelheim / بوهرنجر',
  'Novo Nordisk / نوفو نورديسك',
  'Takeda / تاكيدا',
  'Servier / سيرفييه',
  'SPIMACO / سبيماكو الدوائية',
  'Julphar / جلفار الخليج',
  'Hikma / الحكمة للأدوية',
  'Tabuk / تبوك للصناعات الدوائية',
  'Amoun / آمون للأدوية',
  'Eva Pharma / إيفا فارما',
  'Yemen Pharma / اليمن لصناعة الأدوية',
  'Modern Pharma / الحديثة للأدوية',
  'Sheba Pharma / سبأ فارما'
] as const;

export const ONLINE_DRUG_DIRECTORY: OnlineDrugItem[] = [
  // --- مضادات حيوية وميكروبية ---
  {
    barcode: '6291101000001',
    name: 'أموكسيل 500 ملجم',
    nameEn: 'Amoxil 500mg',
    scientificName: 'Amoxicillin Trihydrate 500mg',
    category: 'مضادات حيوية وميكروبية',
    form: 'كبسولات',
    strength: '500mg',
    manufacturer: 'GSK / جلاكسو سميث كلاين',
    country: 'بريطانيا',
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'A-101',
    standardCost: 1200,
    standardPrice: 1600,
    indications: 'علاج الالتهابات البكتيرية للجهاز التنفسي والمسالك والأذن'
  },
  {
    barcode: '6291101000002',
    name: 'أوجمنتين 1 جم',
    nameEn: 'Augmentin 1g',
    scientificName: 'Amoxicillin + Clavulanic Acid 1000mg',
    category: 'مضادات حيوية وميكروبية',
    form: 'أقراص',
    strength: '1g',
    manufacturer: 'GSK / جلاكسو سميث كلاين',
    country: 'بريطانيا',
    stripsPerPackage: 2,
    piecesPerStrip: 7,
    requiresPrescription: true,
    locationRack: 'A-102',
    standardCost: 3200,
    standardPrice: 4200,
    indications: 'مضاد حيوي واسع المجال لالتهابات الصدر والجيوب والجلد'
  },
  {
    barcode: '6291101000003',
    name: 'أوجمنتين 625 ملجم',
    nameEn: 'Augmentin 625mg',
    scientificName: 'Amoxicillin + Clavulanate 625mg',
    category: 'مضادات حيوية وميكروبية',
    form: 'أقراص',
    strength: '625mg',
    manufacturer: 'GSK / جلاكسو سميث كلاين',
    country: 'بريطانيا',
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'A-103',
    standardCost: 2400,
    standardPrice: 3200,
    indications: 'علاج التهابات الجهاز التنفسي والتهاب اللوزتين'
  },
  {
    barcode: '6291101000004',
    name: 'أزيماك 500 ملجم',
    nameEn: 'Azimax 500mg',
    scientificName: 'Azithromycin 500mg',
    category: 'مضادات حيوية وميكروبية',
    form: 'أقراص',
    strength: '500mg',
    manufacturer: 'SPIMACO / سبيماكو الدوائية',
    country: 'السعودية',
    stripsPerPackage: 1,
    piecesPerStrip: 3,
    requiresPrescription: true,
    locationRack: 'A-104',
    standardCost: 2000,
    standardPrice: 2800,
    indications: 'مضاد حيوي ماكروليدي لعدوى الصدر والجلد والأنسجة'
  },
  {
    barcode: '6291101000005',
    name: 'زيثرون 500 ملجم',
    nameEn: 'Zithrone 500mg',
    scientificName: 'Azithromycin Dihydrate 500mg',
    category: 'مضادات حيوية وميكروبية',
    form: 'أقراص',
    strength: '500mg',
    manufacturer: 'Amoun / آمون للأدوية',
    country: 'مصر',
    stripsPerPackage: 1,
    piecesPerStrip: 3,
    requiresPrescription: true,
    locationRack: 'A-105',
    standardCost: 1500,
    standardPrice: 2100,
    indications: 'علاج النزلات الشعبية والتهاب الجيوب الأنفية'
  },
  {
    barcode: '6291101000006',
    name: 'سيبروكسين 500 ملجم',
    nameEn: 'Ciproxin 500mg',
    scientificName: 'Ciprofloxacin HCl 500mg',
    category: 'مضادات حيوية وميكروبية',
    form: 'أقراص',
    strength: '500mg',
    manufacturer: 'Bayer / باير',
    country: 'ألمانيا',
    stripsPerPackage: 1,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'A-106',
    standardCost: 2200,
    standardPrice: 3000,
    indications: 'علاج التهابات المسالك البولية والجهاز الهضمي والبروستاتا'
  },
  {
    barcode: '6291101000007',
    name: 'فلاجيل 500 ملجم',
    nameEn: 'Flagyl 500mg',
    scientificName: 'Metronidazole 500mg',
    category: 'مضادات حيوية وميكروبية',
    form: 'أقراص',
    strength: '500mg',
    manufacturer: 'Sanofi / سانوفي',
    country: 'فرنسا',
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'A-107',
    standardCost: 1100,
    standardPrice: 1500,
    indications: 'مضاد للطفيليات واللاهوائيات وعلاج الأميبا والجيارديا'
  },
  {
    barcode: '6291101000008',
    name: 'روسيفين 1 جم حقن',
    nameEn: 'Rocephin 1g Vial',
    scientificName: 'Ceftriaxone Sodium 1g',
    category: 'مضادات حيوية وميكروبية',
    form: 'حقن',
    strength: '1g IV/IM',
    manufacturer: 'Roche / روش',
    country: 'سويسرا',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: true,
    locationRack: 'A-108',
    standardCost: 3500,
    standardPrice: 4800,
    indications: 'سيفالوسبورين جيل ثالث للعدوى البكتيرية الحادة والتسمم'
  },
  {
    barcode: '6291101000009',
    name: 'سوبراكس 400 ملجم',
    nameEn: 'Suprax 400mg',
    scientificName: 'Cefixime 400mg',
    category: 'مضادات حيوية وميكروبية',
    form: 'كبسولات',
    strength: '400mg',
    manufacturer: 'Hikma / الحكمة للأدوية',
    country: 'الأردن',
    stripsPerPackage: 1,
    piecesPerStrip: 5,
    requiresPrescription: true,
    locationRack: 'A-109',
    standardCost: 2800,
    standardPrice: 3800,
    indications: 'مضاد حيوي فعال للالتهابات الرئوية والمسالك البولية'
  },
  {
    barcode: '6291101000010',
    name: 'كلاسيد 500 ملجم',
    nameEn: 'Klacid 500mg',
    scientificName: 'Clarithromycin 500mg',
    category: 'مضادات حيوية وميكروبية',
    form: 'أقراص',
    strength: '500mg',
    manufacturer: 'Abbott / أبوت',
    country: 'أمريكا',
    stripsPerPackage: 2,
    piecesPerStrip: 7,
    requiresPrescription: true,
    locationRack: 'A-110',
    standardCost: 4500,
    standardPrice: 6000,
    indications: 'علاج جرثومة المعدة H.Pylori والتهابات الجهاز التنفسي'
  },
  {
    barcode: '6291101000011',
    name: 'فيبراميسين 100 ملجم',
    nameEn: 'Vibramycin 100mg',
    scientificName: 'Doxycycline Hyclate 100mg',
    category: 'مضادات حيوية وميكروبية',
    form: 'كبسولات',
    strength: '100mg',
    manufacturer: 'Pfizer / فايزر',
    country: 'أمريكا',
    stripsPerPackage: 1,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'A-111',
    standardCost: 900,
    standardPrice: 1300,
    indications: 'علاج حب الشباب وعدوى الجلد والصدر والأمراض المنتقلة'
  },
  {
    barcode: '6291101000012',
    name: 'ديفلوكان 150 ملجم',
    nameEn: 'Diflucan 150mg',
    scientificName: 'Fluconazole 150mg',
    category: 'مضادات حيوية وميكروبية',
    form: 'كبسولات',
    strength: '150mg',
    manufacturer: 'Pfizer / فايزر',
    country: 'أمريكا',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: false,
    locationRack: 'A-112',
    standardCost: 2000,
    standardPrice: 2800,
    indications: 'مضاد فطريات واسع الطيف للالتهابات الفطرية والكانديدا'
  },
  {
    barcode: '6291101000013',
    name: 'زوفيراكس 400 ملجم',
    nameEn: 'Zovirax 400mg',
    scientificName: 'Acyclovir 400mg',
    category: 'مضادات حيوية وميكروبية',
    form: 'أقراص',
    strength: '400mg',
    manufacturer: 'GSK / جلاكسو سميث كلاين',
    country: 'بريطانيا',
    stripsPerPackage: 5,
    piecesPerStrip: 5,
    requiresPrescription: true,
    locationRack: 'A-113',
    standardCost: 3200,
    standardPrice: 4400,
    indications: 'مضاد فيروسات لعلاج الهربس البسيط والحزام الناري'
  },

  // --- مسكنات ومضادات التهاب ---
  {
    barcode: '6291101000020',
    name: 'بنادول أزرق 500 ملجم',
    nameEn: 'Panadol Blue 500mg',
    scientificName: 'Paracetamol 500mg',
    category: 'مسكنات ومضادات التهاب',
    form: 'أقراص',
    strength: '500mg',
    manufacturer: 'GSK / جلاكسو سميث كلاين',
    country: 'بريطانيا',
    stripsPerPackage: 2,
    piecesPerStrip: 12,
    requiresPrescription: false,
    locationRack: 'B-101',
    standardCost: 800,
    standardPrice: 1100,
    indications: 'مسكن للآلام وخافض للحرارة آمن للمعدة'
  },
  {
    barcode: '6291101000021',
    name: 'بنادول إكسترا أحمر',
    nameEn: 'Panadol Extra Red',
    scientificName: 'Paracetamol 500mg + Caffeine 65mg',
    category: 'مسكنات ومضادات التهاب',
    form: 'أقراص',
    strength: '500/65mg',
    manufacturer: 'GSK / جلاكسو سميث كلاين',
    country: 'بريطانيا',
    stripsPerPackage: 2,
    piecesPerStrip: 12,
    requiresPrescription: false,
    locationRack: 'B-102',
    standardCost: 1100,
    standardPrice: 1500,
    indications: 'مسكن قوي للصداع الشديد وآلام الأسنان والجسم'
  },
  {
    barcode: '6291101000022',
    name: 'بروفين 400 ملجم',
    nameEn: 'Brufen 400mg',
    scientificName: 'Ibuprofen 400mg',
    category: 'مسكنات ومضادات التهاب',
    form: 'أقراص',
    strength: '400mg',
    manufacturer: 'Abbott / أبوت',
    country: 'أمريكا',
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'B-103',
    standardCost: 1200,
    standardPrice: 1700,
    indications: 'مسكن ومضاد للالتهاب والتورم وخافض حرارة'
  },
  {
    barcode: '6291101000023',
    name: 'بروفين 600 ملجم',
    nameEn: 'Brufen 600mg',
    scientificName: 'Ibuprofen 600mg',
    category: 'مسكنات ومضادات التهاب',
    form: 'أقراص',
    strength: '600mg',
    manufacturer: 'Abbott / أبوت',
    country: 'أمريكا',
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'B-104',
    standardCost: 1600,
    standardPrice: 2200,
    indications: 'تسكين آلام المفاصل والعمود الفقري والأسنان'
  },
  {
    barcode: '6291101000024',
    name: 'فولتارين 50 ملجم',
    nameEn: 'Voltaren 50mg',
    scientificName: 'Diclofenac Sodium 50mg',
    category: 'مسكنات ومضادات التهاب',
    form: 'أقراص',
    strength: '50mg',
    manufacturer: 'Novartis / نوفارتس',
    country: 'سويسرا',
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'B-105',
    standardCost: 1800,
    standardPrice: 2500,
    indications: 'مضاد التهاب غير ستيرويدي لآلام الروماتيزم والرضوض'
  },
  {
    barcode: '6291101000025',
    name: 'فولتارين 75 ملجم حقن',
    nameEn: 'Voltaren 75mg Ampoule',
    scientificName: 'Diclofenac Sodium 75mg/3ml',
    category: 'مسكنات ومضادات التهاب',
    form: 'حقن',
    strength: '75mg/3ml',
    manufacturer: 'Novartis / نوفارتس',
    country: 'سويسرا',
    stripsPerPackage: 1,
    piecesPerStrip: 5,
    requiresPrescription: true,
    locationRack: 'B-106',
    standardCost: 2200,
    standardPrice: 3100,
    indications: 'تسكين فوري لنوبات المغص الكلوي والآلام الحادة'
  },
  {
    barcode: '6291101000026',
    name: 'فولتارين إيمولجل',
    nameEn: 'Voltaren Emulgel 50g',
    scientificName: 'Diclofenac Diethylamine 1.16%',
    category: 'مسكنات ومضادات التهاب',
    form: 'جل',
    strength: '1.16% 50g',
    manufacturer: 'Novartis / نوفارتس',
    country: 'سويسرا',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: false,
    locationRack: 'B-107',
    standardCost: 1900,
    standardPrice: 2600,
    indications: 'مسكن موضعي لآلام العضلات والمفاصل والتواء الأربطة'
  },
  {
    barcode: '6291101000027',
    name: 'كتافلام 50 ملجم',
    nameEn: 'Cataflam 50mg',
    scientificName: 'Diclofenac Potassium 50mg',
    category: 'مسكنات ومضادات التهاب',
    form: 'أقراص',
    strength: '50mg',
    manufacturer: 'Novartis / نوفارتس',
    country: 'سويسرا',
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'B-108',
    standardCost: 2000,
    standardPrice: 2700,
    indications: 'سريع المفعول لتسكين آلام الدورة الشهرية والأسنان'
  },
  {
    barcode: '6291101000028',
    name: 'سيليبريكس 200 ملجم',
    nameEn: 'Celebrex 200mg',
    scientificName: 'Celecoxib 200mg',
    category: 'مسكنات ومضادات التهاب',
    form: 'كبسولات',
    strength: '200mg',
    manufacturer: 'Pfizer / فايزر',
    country: 'أمريكا',
    stripsPerPackage: 1,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'B-109',
    standardCost: 4200,
    standardPrice: 5600,
    indications: 'مثبط انتقائي COX-2 آمن للمعدة لخشونة الركبة والمفاصل'
  },
  {
    barcode: '6291101000029',
    name: 'نابروسين 500 ملجم',
    nameEn: 'Naprosyn 500mg',
    scientificName: 'Naproxen 500mg',
    category: 'مسكنات ومضادات التهاب',
    form: 'أقراص',
    strength: '500mg',
    manufacturer: 'Roche / روش',
    country: 'سويسرا',
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'B-110',
    standardCost: 2100,
    standardPrice: 2900,
    indications: 'مضاد للالتهاب ممتد المفعول للنقرس والصداع النصفي'
  },
  {
    barcode: '6291101000030',
    name: 'فيلدين 20 ملجم',
    nameEn: 'Feldene 20mg',
    scientificName: 'Piroxicam 20mg',
    category: 'مسكنات ومضادات التهاب',
    form: 'كبسولات',
    strength: '20mg',
    manufacturer: 'Pfizer / فايزر',
    country: 'أمريكا',
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'B-111',
    standardCost: 1500,
    standardPrice: 2100,
    indications: 'علاج التهاب المفاصل الروماتويدي وتيبس الفقرات'
  },

  // --- أدوية الضغط والقلب والأوعية ---
  {
    barcode: '6291101000040',
    name: 'كونكور 5 ملجم',
    nameEn: 'Concor 5mg',
    scientificName: 'Bisoprolol Fumarate 5mg',
    category: 'أدوية الضغط والقلب والأوعية',
    form: 'أقراص',
    strength: '5mg',
    manufacturer: 'Merck / ميرك',
    country: 'ألمانيا',
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'C-101',
    standardCost: 3100,
    standardPrice: 4200,
    indications: 'منظم لضربات القلب وعلاج ارتفاع ضغط الدم والذبحة'
  },
  {
    barcode: '6291101000041',
    name: 'كونكور 2.5 ملجم',
    nameEn: 'Concor 2.5mg',
    scientificName: 'Bisoprolol Fumarate 2.5mg',
    category: 'أدوية الضغط والقلب والأوعية',
    form: 'أقراص',
    strength: '2.5mg',
    manufacturer: 'Merck / ميرك',
    country: 'ألمانيا',
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'C-102',
    standardCost: 2600,
    standardPrice: 3500,
    indications: 'علاج قصور عضلة القلب وارتفاع الضغط البسيط'
  },
  {
    barcode: '6291101000042',
    name: 'نورفاسك 5 ملجم',
    nameEn: 'Norvasc 5mg',
    scientificName: 'Amlodipine Besylate 5mg',
    category: 'أدوية الضغط والقلب والأوعية',
    form: 'أقراص',
    strength: '5mg',
    manufacturer: 'Pfizer / فايزر',
    country: 'أمريكا',
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'C-103',
    standardCost: 3500,
    standardPrice: 4800,
    indications: 'موسع للأوعية الدموية وعلاج ضغط الدم الشرياني'
  },
  {
    barcode: '6291101000043',
    name: 'نورفاسك 10 ملجم',
    nameEn: 'Norvasc 10mg',
    scientificName: 'Amlodipine Besylate 10mg',
    category: 'أدوية الضغط والقلب والأوعية',
    form: 'أقراص',
    strength: '10mg',
    manufacturer: 'Pfizer / فايزر',
    country: 'أمريكا',
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'C-104',
    standardCost: 4600,
    standardPrice: 6200,
    indications: 'علاج حالات ارتفاع ضغط الدم المتقدمة والذبحة الصدرية'
  },
  {
    barcode: '6291101000044',
    name: 'كوزار 50 ملجم',
    nameEn: 'Cozaar 50mg',
    scientificName: 'Losartan Potassium 50mg',
    category: 'أدوية الضغط والقلب والأوعية',
    form: 'أقراص',
    strength: '50mg',
    manufacturer: 'Merck / ميرك',
    country: 'أمريكا',
    stripsPerPackage: 2,
    piecesPerStrip: 14,
    requiresPrescription: true,
    locationRack: 'C-105',
    standardCost: 3800,
    standardPrice: 5100,
    indications: 'حماية الكلى لمرضى السكري والضغط'
  },
  {
    barcode: '6291101000045',
    name: 'ديوفان 80 ملجم',
    nameEn: 'Diovan 80mg',
    scientificName: 'Valsartan 80mg',
    category: 'أدوية الضغط والقلب والأوعية',
    form: 'أقراص',
    strength: '80mg',
    manufacturer: 'Novartis / نوفارتس',
    country: 'سويسرا',
    stripsPerPackage: 2,
    piecesPerStrip: 14,
    requiresPrescription: true,
    locationRack: 'C-106',
    standardCost: 4000,
    standardPrice: 5400,
    indications: 'خفض ضغط الدم وتقليل إجهاد عضلة القلب'
  },
  {
    barcode: '6291101000046',
    name: 'كابوتن 25 ملجم',
    nameEn: 'Capoten 25mg',
    scientificName: 'Captopril 25mg',
    category: 'أدوية الضغط والقلب والأوعية',
    form: 'أقراص',
    strength: '25mg',
    manufacturer: 'Bristol-Myers Squibb',
    country: 'أمريكا',
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'C-107',
    standardCost: 1200,
    standardPrice: 1700,
    indications: 'علاج طوارئ ارتفاع الضغط تحت اللسان'
  },
  {
    barcode: '6291101000047',
    name: 'ليبيتور 20 ملجم',
    nameEn: 'Lipitor 20mg',
    scientificName: 'Atorvastatin Calcium 20mg',
    category: 'أدوية الضغط والقلب والأوعية',
    form: 'أقراص',
    strength: '20mg',
    manufacturer: 'Pfizer / فايزر',
    country: 'أمريكا',
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'C-108',
    standardCost: 5200,
    standardPrice: 7000,
    indications: 'خفض الكوليسترول الضار والدهون الثلاثية وحماية الشرايين'
  },
  {
    barcode: '6291101000048',
    name: 'كريستور 10 ملجم',
    nameEn: 'Crestor 10mg',
    scientificName: 'Rosuvastatin Calcium 10mg',
    category: 'أدوية الضغط والقلب والأوعية',
    form: 'أقراص',
    strength: '10mg',
    manufacturer: 'AstraZeneca / أسترازينيكا',
    country: 'بريطانيا',
    stripsPerPackage: 2,
    piecesPerStrip: 14,
    requiresPrescription: true,
    locationRack: 'C-109',
    standardCost: 6500,
    standardPrice: 8700,
    indications: 'أقوى مخفضات الكوليسترول لحماية مرضى القلب والجلطات'
  },
  {
    barcode: '6291101000049',
    name: 'بلافيكس 75 ملجم',
    nameEn: 'Plavix 75mg',
    scientificName: 'Clopidogrel Bisulfate 75mg',
    category: 'أدوية الضغط والقلب والأوعية',
    form: 'أقراص',
    strength: '75mg',
    manufacturer: 'Sanofi / سانوفي',
    country: 'فرنسا',
    stripsPerPackage: 2,
    piecesPerStrip: 14,
    requiresPrescription: true,
    locationRack: 'C-110',
    standardCost: 6000,
    standardPrice: 8000,
    indications: 'مانع لتجلط الدم وتراكم الصفائح الدموية بعد القسطرة والدعامات'
  },
  {
    barcode: '6291101000050',
    name: 'أسبرين بروتكت 100 ملجم',
    nameEn: 'Aspirin Protect 100mg',
    scientificName: 'Acetylsalicylic Acid 100mg',
    category: 'أدوية الضغط والقلب والأوعية',
    form: 'أقراص',
    strength: '100mg',
    manufacturer: 'Bayer / باير',
    country: 'ألمانيا',
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'C-111',
    standardCost: 1100,
    standardPrice: 1500,
    indications: 'مسيل دم وقائي مغلف لحماية المعدة ومنع الجلطات'
  },
  {
    barcode: '6291101000051',
    name: 'لازيكس 40 ملجم',
    nameEn: 'Lasix 40mg',
    scientificName: 'Furosemide 40mg',
    category: 'أدوية الضغط والقلب والأوعية',
    form: 'أقراص',
    strength: '40mg',
    manufacturer: 'Sanofi / سانوفي',
    country: 'فرنسا',
    stripsPerPackage: 2,
    piecesPerStrip: 12,
    requiresPrescription: true,
    locationRack: 'C-112',
    standardCost: 900,
    standardPrice: 1300,
    indications: 'مدر قوي للبول والتخلص من احتباس السوائل وتورم القدمين'
  },

  // --- أدوية السكري والغدد ---
  {
    barcode: '6291101000060',
    name: 'جلوكوفاج 500 ملجم',
    nameEn: 'Glucophage 500mg',
    scientificName: 'Metformin Hydrochloride 500mg',
    category: 'أدوية السكري والغدد',
    form: 'أقراص',
    strength: '500mg',
    manufacturer: 'Merck / ميرك',
    country: 'فرنسا',
    stripsPerPackage: 5,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'D-101',
    standardCost: 1500,
    standardPrice: 2000,
    indications: 'علاج الخط الأول لمرض السكري النوع الثاني وتحسين حساسية الإنسولين'
  },
  {
    barcode: '6291101000061',
    name: 'جلوكوفاج 850 ملجم',
    nameEn: 'Glucophage 850mg',
    scientificName: 'Metformin HCl 850mg',
    category: 'أدوية السكري والغدد',
    form: 'أقراص',
    strength: '850mg',
    manufacturer: 'Merck / ميرك',
    country: 'فرنسا',
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'D-102',
    standardCost: 1800,
    standardPrice: 2400,
    indications: 'ضبط مستوى السكر التراكمي وتكيس المبايض'
  },
  {
    barcode: '6291101000062',
    name: 'جلوكوفاج إكس آر 1000 ملجم',
    nameEn: 'Glucophage XR 1000mg',
    scientificName: 'Metformin HCl XR 1000mg',
    category: 'أدوية السكري والغدد',
    form: 'أقراص',
    strength: '1000mg XR',
    manufacturer: 'Merck / ميرك',
    country: 'فرنسا',
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'D-103',
    standardCost: 2800,
    standardPrice: 3800,
    indications: 'ممتد المفعول مرة يومياً لطيف على الجهاز الهضمي'
  },
  {
    barcode: '6291101000063',
    name: 'أماريل 2 ملجم',
    nameEn: 'Amaryl 2mg',
    scientificName: 'Glimepiride 2mg',
    category: 'أدوية السكري والغدد',
    form: 'أقراص',
    strength: '2mg',
    manufacturer: 'Sanofi / سانوفي',
    country: 'ألمانيا',
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'D-104',
    standardCost: 2500,
    standardPrice: 3400,
    indications: 'تحفيز إفراز الإنسولين من خلايا البنكرياس'
  },
  {
    barcode: '6291101000064',
    name: 'جانوفيا 100 ملجم',
    nameEn: 'Januvia 100mg',
    scientificName: 'Sitagliptin Phosphate 100mg',
    category: 'أدوية السكري والغدد',
    form: 'أقراص',
    strength: '100mg',
    manufacturer: 'Merck / ميرك',
    country: 'أمريكا',
    stripsPerPackage: 2,
    piecesPerStrip: 14,
    requiresPrescription: true,
    locationRack: 'D-105',
    standardCost: 9500,
    standardPrice: 12500,
    indications: 'مثبط DPP-4 الذكي بدون التسبب في هبوط حاد للسكر'
  },
  {
    barcode: '6291101000065',
    name: 'فورسيجا 10 ملجم',
    nameEn: 'Forxiga 10mg',
    scientificName: 'Dapagliflozin 10mg',
    category: 'أدوية السكري والغدد',
    form: 'أقراص',
    strength: '10mg',
    manufacturer: 'AstraZeneca / أسترازينيكا',
    country: 'بريطانيا',
    stripsPerPackage: 2,
    piecesPerStrip: 14,
    requiresPrescription: true,
    locationRack: 'D-106',
    standardCost: 11000,
    standardPrice: 14500,
    indications: 'طرح السكر الزائد عن طريق الكلى وحماية القلب'
  },
  {
    barcode: '6291101000066',
    name: 'إلتروكسين 50 ميكروجرام',
    nameEn: 'Eltroxin 50mcg',
    scientificName: 'Levothyroxine Sodium 50mcg',
    category: 'أدوية السكري والغدد',
    form: 'أقراص',
    strength: '50mcg',
    manufacturer: 'GSK / جلاكسو سميث كلاين',
    country: 'بريطانيا',
    stripsPerPackage: 2,
    piecesPerStrip: 25,
    requiresPrescription: true,
    locationRack: 'D-107',
    standardCost: 1400,
    standardPrice: 1900,
    indications: 'هرمون تعويضي لعلاج خمول وكسل الغدة الدرقية'
  },
  {
    barcode: '6291101000067',
    name: 'إلتروكسين 100 ميكروجرام',
    nameEn: 'Eltroxin 100mcg',
    scientificName: 'Levothyroxine Sodium 100mcg',
    category: 'أدوية السكري والغدد',
    form: 'أقراص',
    strength: '100mcg',
    manufacturer: 'GSK / جلاكسو سميث كلاين',
    country: 'بريطانيا',
    stripsPerPackage: 2,
    piecesPerStrip: 25,
    requiresPrescription: true,
    locationRack: 'D-108',
    standardCost: 1800,
    standardPrice: 2400,
    indications: 'علاج قصور الدرقية وتضخم الغدة'
  },
  {
    barcode: '6291101000068',
    name: 'إنسولين لانتوس سولوستار',
    nameEn: 'Lantus SoloStar Pen',
    scientificName: 'Insulin Glargine 100 U/ml',
    category: 'أدوية السكري والغدد',
    form: 'حقن',
    strength: '100 U/ml',
    manufacturer: 'Sanofi / سانوفي',
    country: 'ألمانيا',
    stripsPerPackage: 1,
    piecesPerStrip: 5,
    requiresPrescription: true,
    locationRack: 'D-109',
    standardCost: 16000,
    standardPrice: 21000,
    indications: 'إنسولين قاعدي ممتد المفعول 24 ساعة لمرضى السكري'
  },
  {
    barcode: '6291101000069',
    name: 'إنسولين نوفورابيد فليكسبن',
    nameEn: 'NovoRapid FlexPen',
    scientificName: 'Insulin Aspart 100 U/ml',
    category: 'أدوية السكري والغدد',
    form: 'حقن',
    strength: '100 U/ml',
    manufacturer: 'Novo Nordisk / نوفو نورديسك',
    country: 'الدنمارك',
    stripsPerPackage: 1,
    piecesPerStrip: 5,
    requiresPrescription: true,
    locationRack: 'D-110',
    standardCost: 15500,
    standardPrice: 20500,
    indications: 'إنسولين سريع المفعول للوجبات الغذائية'
  },

  // --- أدوية الجهاز الهضمي والمعدة ---
  {
    barcode: '6291101000080',
    name: 'نيكسيوم 40 ملجم',
    nameEn: 'Nexium 40mg',
    scientificName: 'Esomeprazole Magnesium 40mg',
    category: 'أدوية الجهاز الهضمي والمعدة',
    form: 'أقراص',
    strength: '40mg',
    manufacturer: 'AstraZeneca / أسترازينيكا',
    country: 'السويد',
    stripsPerPackage: 2,
    piecesPerStrip: 14,
    requiresPrescription: false,
    locationRack: 'E-101',
    standardCost: 6500,
    standardPrice: 8800,
    indications: 'علاج قرحة المعدة وارتجاع المريء الشديد والحموضة'
  },
  {
    barcode: '6291101000081',
    name: 'نيكسيوم 20 ملجم',
    nameEn: 'Nexium 20mg',
    scientificName: 'Esomeprazole 20mg',
    category: 'أدوية الجهاز الهضمي والمعدة',
    form: 'أقراص',
    strength: '20mg',
    manufacturer: 'AstraZeneca / أسترازينيكا',
    country: 'السويد',
    stripsPerPackage: 2,
    piecesPerStrip: 14,
    requiresPrescription: false,
    locationRack: 'E-102',
    standardCost: 5200,
    standardPrice: 7000,
    indications: 'وقاية المعدة من تأثير المسكنات وعلاج الحموضة'
  },
  {
    barcode: '6291101000082',
    name: 'كونترولوك 40 ملجم',
    nameEn: 'Controloc 40mg',
    scientificName: 'Pantoprazole Sodium 40mg',
    category: 'أدوية الجهاز الهضمي والمعدة',
    form: 'أقراص',
    strength: '40mg',
    manufacturer: 'Takeda / تاكيدا',
    country: 'ألمانيا',
    stripsPerPackage: 2,
    piecesPerStrip: 14,
    requiresPrescription: false,
    locationRack: 'E-103',
    standardCost: 4800,
    standardPrice: 6500,
    indications: 'علاج التهاب المعدة والتآكل الحمضي للمريء'
  },
  {
    barcode: '6291101000083',
    name: 'أوميز 20 ملجم',
    nameEn: 'Omez 20mg',
    scientificName: 'Omeprazole 20mg',
    category: 'أدوية الجهاز الهضمي والمعدة',
    form: 'كبسولات',
    strength: '20mg',
    manufacturer: 'Julphar / جلفار الخليج',
    country: 'الإمارات',
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'E-104',
    standardCost: 1400,
    standardPrice: 1900,
    indications: 'تخفيف حرقان المعدة والانتفاخ الحمضي'
  },
  {
    barcode: '6291101000084',
    name: 'جافيسكون شراب أصلي',
    nameEn: 'Gaviscon Original Liquid 200ml',
    scientificName: 'Sodium Alginate + Sodium Bicarbonate',
    category: 'أدوية الجهاز الهضمي والمعدة',
    form: 'شراب',
    strength: '200ml',
    manufacturer: 'Reckitt Benckiser',
    country: 'بريطانيا',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: false,
    locationRack: 'E-105',
    standardCost: 2400,
    standardPrice: 3200,
    indications: 'حاجز واقي فوري ضد الارتجاع المريئي وحموضة الحوامل'
  },
  {
    barcode: '6291101000085',
    name: 'موتيليوم 10 ملجم',
    nameEn: 'Motilium 10mg',
    scientificName: 'Domperidone 10mg',
    category: 'أدوية الجهاز الهضمي والمعدة',
    form: 'أقراص',
    strength: '10mg',
    manufacturer: 'Janssen / يانسن',
    country: 'بلجيكا',
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'E-106',
    standardCost: 2000,
    standardPrice: 2800,
    indications: 'تنظيم حركة المعدة وعلاج الغثيان والامتلاء'
  },
  {
    barcode: '6291101000086',
    name: 'دوسباتالين ريتارد 200 ملجم',
    nameEn: 'Duspatalin Retard 200mg',
    scientificName: 'Mebeverine Hydrochloride 200mg',
    category: 'أدوية الجهاز الهضمي والمعدة',
    form: 'كبسولات',
    strength: '200mg',
    manufacturer: 'Abbott / أبوت',
    country: 'هولندا',
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'E-107',
    standardCost: 3800,
    standardPrice: 5100,
    indications: 'العلاج النوعي لتقلصات وانتفاخات القولون العصبي IBS'
  },
  {
    barcode: '6291101000087',
    name: 'سبازموديجستين أقراص',
    nameEn: 'Spasmo-Digestin',
    scientificName: 'Dicyclomine + Papain + Simethicone',
    category: 'أدوية الجهاز الهضمي والمعدة',
    form: 'أقراص',
    strength: 'Compound',
    manufacturer: 'Eva Pharma / إيفا فارما',
    country: 'مصر',
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'E-108',
    standardCost: 1100,
    standardPrice: 1500,
    indications: 'مهضم ومهدئ لغازات وتطبل البطن والقولون'
  },
  {
    barcode: '6291101000088',
    name: 'إيموديوم 2 ملجم',
    nameEn: 'Imodium 2mg',
    scientificName: 'Loperamide HCl 2mg',
    category: 'أدوية الجهاز الهضمي والمعدة',
    form: 'كبسولات',
    strength: '2mg',
    manufacturer: 'Johnson & Johnson',
    country: 'أمريكا',
    stripsPerPackage: 1,
    piecesPerStrip: 6,
    requiresPrescription: false,
    locationRack: 'E-109',
    standardCost: 1200,
    standardPrice: 1700,
    indications: 'علاج سريع لحالات الإسهال الحاد والمسافرين'
  },
  {
    barcode: '6291101000089',
    name: 'دوفالاك شراب 200 مل',
    nameEn: 'Duphalac Syrup 200ml',
    scientificName: 'Lactulose 66.7g/100ml',
    category: 'أدوية الجهاز الهضمي والمعدة',
    form: 'شراب',
    strength: '200ml',
    manufacturer: 'Abbott / أبوت',
    country: 'هولندا',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: false,
    locationRack: 'E-110',
    standardCost: 2100,
    standardPrice: 2900,
    indications: 'ملين لطيف آمن للحوامل والأطفال وكبار السن'
  },

  // --- أدوية الجهاز التنفسي والبرد والحساسية ---
  {
    barcode: '6291101000100',
    name: 'فينتولين بخاخ 100 ميكروجرام',
    nameEn: 'Ventolin Evohaler 100mcg',
    scientificName: 'Salbutamol Inhaler 100mcg',
    category: 'أدوية الجهاز التنفسي والبرد والحساسية',
    form: 'بخاخ',
    strength: '100mcg (200 doses)',
    manufacturer: 'GSK / جلاكسو سميث كلاين',
    country: 'بريطانيا',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: true,
    locationRack: 'F-101',
    standardCost: 2800,
    standardPrice: 3800,
    indications: 'موسع قصبي فوري لأزمات الربو وضيق التنفس الحاد'
  },
  {
    barcode: '6291101000101',
    name: 'سيمبيكورت توربوهيلر 160/4.5',
    nameEn: 'Symbicort Turbuhaler 160/4.5',
    scientificName: 'Budesonide + Formoterol',
    category: 'أدوية الجهاز التنفسي والبرد والحساسية',
    form: 'بخاخ',
    strength: '160/4.5mcg (120 doses)',
    manufacturer: 'AstraZeneca / أسترازينيكا',
    country: 'السويد',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: true,
    locationRack: 'F-102',
    standardCost: 14000,
    standardPrice: 18500,
    indications: 'وقائي وعلاجي لمرضى الربو والانسداد الرئوي المزمن COPD'
  },
  {
    barcode: '6291101000102',
    name: 'كلاريتين 10 ملجم',
    nameEn: 'Claritin 10mg',
    scientificName: 'Loratadine 10mg',
    category: 'أدوية الجهاز التنفسي والبرد والحساسية',
    form: 'أقراص',
    strength: '10mg',
    manufacturer: 'Bayer / باير',
    country: 'ألمانيا',
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'F-103',
    standardCost: 2200,
    standardPrice: 3000,
    indications: 'مضاد حساسية لا يسبب النعاس لعطاس وحكة الجيوب'
  },
  {
    barcode: '6291101000103',
    name: 'زيرتك 10 ملجم',
    nameEn: 'Zyrtec 10mg',
    scientificName: 'Cetirizine Hydrochloride 10mg',
    category: 'أدوية الجهاز التنفسي والبرد والحساسية',
    form: 'أقراص',
    strength: '10mg',
    manufacturer: 'UCB Pharma / يو سي بي',
    country: 'بلجيكا',
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'F-104',
    standardCost: 2000,
    standardPrice: 2700,
    indications: 'علاج حساسية الأنف والارتكاريا وحكة الجلد'
  },
  {
    barcode: '6291101000104',
    name: 'إريوس 5 ملجم',
    nameEn: 'Aerius 5mg',
    scientificName: 'Desloratadine 5mg',
    category: 'أدوية الجهاز التنفسي والبرد والحساسية',
    form: 'أقراص',
    strength: '5mg',
    manufacturer: 'Bayer / باير',
    country: 'ألمانيا',
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'F-105',
    standardCost: 2900,
    standardPrice: 3900,
    indications: 'الجيل الأحدث لمضادات الهيستامين بدون نعاس إطلاقاً'
  },
  {
    barcode: '6291101000105',
    name: 'تلفاست 180 ملجم',
    nameEn: 'Telfast 180mg',
    scientificName: 'Fexofenadine HCl 180mg',
    category: 'أدوية الجهاز التنفسي والبرد والحساسية',
    form: 'أقراص',
    strength: '180mg',
    manufacturer: 'Sanofi / سانوفي',
    country: 'فرنسا',
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'F-106',
    standardCost: 3200,
    standardPrice: 4300,
    indications: 'علاج الأرتيكاريا والحساسية الجلدية المزمنة'
  },
  {
    barcode: '6291101000106',
    name: 'أوترفين بخاخ للكبار 0.1%',
    nameEn: 'Otrivin Adult Spray 0.1%',
    scientificName: 'Xylometazoline HCl 0.1%',
    category: 'أدوية الجهاز التنفسي والبرد والحساسية',
    form: 'بخاخ',
    strength: '0.1% 10ml',
    manufacturer: 'Haleon / GSK',
    country: 'سويسرا',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: false,
    locationRack: 'F-107',
    standardCost: 1400,
    standardPrice: 1900,
    indications: 'مزيل لاحتقان الأنف خلال دقيقتين'
  },
  {
    barcode: '6291101000107',
    name: 'فلودريكس أقراص',
    nameEn: 'Fludrex Tablets',
    scientificName: 'Paracetamol + Pseudoephedrine + Chlorpheniramine',
    category: 'أدوية الجهاز التنفسي والبرد والحساسية',
    form: 'أقراص',
    strength: 'Triple Formula',
    manufacturer: 'SPIMACO / سبيماكو الدوائية',
    country: 'السعودية',
    stripsPerPackage: 2,
    piecesPerStrip: 12,
    requiresPrescription: false,
    locationRack: 'F-108',
    standardCost: 1300,
    standardPrice: 1800,
    indications: 'علاج شامل لأعراض نزلات البرد والزكام والصداع'
  },
  {
    barcode: '6291101000108',
    name: 'بروسبان شراب للكحة',
    nameEn: 'Prospan Cough Syrup',
    scientificName: 'Dried Ivy Leaf Extract (عشبة اللبلاب)',
    category: 'أدوية الجهاز التنفسي والبرد والحساسية',
    form: 'شراب',
    strength: '100ml',
    manufacturer: 'Engelhard / إنجلهارد',
    country: 'ألمانيا',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: false,
    locationRack: 'F-109',
    standardCost: 2600,
    standardPrice: 3500,
    indications: 'طبيعي مذيب ومطرد للبلغم ومهدئ للسعال'
  },
  {
    barcode: '6291101000109',
    name: 'أولفنت شراب للسعال',
    nameEn: 'All-Vent Syrup',
    scientificName: 'Bromhexine + Guaifenesin + Terbutaline',
    category: 'أدوية الجهاز التنفسي والبرد والحساسية',
    form: 'شراب',
    strength: '120ml',
    manufacturer: 'Medical Union / المهن الطبية',
    country: 'مصر',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: false,
    locationRack: 'F-110',
    standardCost: 1200,
    standardPrice: 1700,
    indications: 'موسع للشعب الهوائية ومذيب للبلغم اللزج'
  },

  // --- الفيتامينات والمكملات الغذائية والمعادن ---
  {
    barcode: '6291101000120',
    name: 'نيوروبيون أقراص (فيتامين ب مركب)',
    nameEn: 'Neurobion Tablets',
    scientificName: 'Vitamin B1 + B6 + B12',
    category: 'الفيتامينات والمكملات الغذائية والمعادن',
    form: 'أقراص',
    strength: 'B Complex Forte',
    manufacturer: 'Merck / ميرك',
    country: 'ألمانيا',
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'G-101',
    standardCost: 2200,
    standardPrice: 3000,
    indications: 'تقوية وتغذية الأعصاب الطرفية لمرضى السكري والإجهاد'
  },
  {
    barcode: '6291101000121',
    name: 'نيوروبيون حقن (أمبولات)',
    nameEn: 'Neurobion Ampoules',
    scientificName: 'Vitamin B1 + B6 + B12 Injectable',
    category: 'الفيتامينات والمكملات الغذائية والمعادن',
    form: 'حقن',
    strength: '3 Ampoules',
    manufacturer: 'Merck / ميرك',
    country: 'ألمانيا',
    stripsPerPackage: 1,
    piecesPerStrip: 3,
    requiresPrescription: false,
    locationRack: 'G-102',
    standardCost: 1800,
    standardPrice: 2500,
    indications: 'علاج فوري لالتهاب عرق النسا وتنميل الأطراف'
  },
  {
    barcode: '6291101000122',
    name: 'فيتامين د3 - 50,000 وحدة',
    nameEn: 'Vitamin D3 50,000 IU',
    scientificName: 'Cholecalciferol 50,000 IU',
    category: 'الفيتامينات والمكملات الغذائية والمعادن',
    form: 'كبسولات',
    strength: '50,000 IU',
    manufacturer: 'Tabuk / تبوك للصناعات الدوائية',
    country: 'السعودية',
    stripsPerPackage: 2,
    piecesPerStrip: 4,
    requiresPrescription: false,
    locationRack: 'G-103',
    standardCost: 3600,
    standardPrice: 4900,
    indications: 'علاج نقص فيتامين د الحاد وهشاشة العظام مرة أسبوعياً'
  },
  {
    barcode: '6291101000123',
    name: 'سنتروم مع لوتين للكبار',
    nameEn: 'Centrum with Lutein Adults',
    scientificName: 'Multivitamins + Minerals + Lutein',
    category: 'الفيتامينات والمكملات الغذائية والمعادن',
    form: 'أقراص',
    strength: '30 Tablets',
    manufacturer: 'Pfizer / فايزر',
    country: 'أمريكا',
    stripsPerPackage: 1,
    piecesPerStrip: 30,
    requiresPrescription: false,
    locationRack: 'G-104',
    standardCost: 4500,
    standardPrice: 6200,
    indications: 'مكمل غذائي يومي متكامل لتعزيز النشاط والمناعة'
  },
  {
    barcode: '6291101000124',
    name: 'كالسيترون كبسولات',
    nameEn: 'Calcitron Capsules',
    scientificName: 'Calcium + Magnesium + Zinc + Vit D3',
    category: 'الفيتامينات والمكملات الغذائية والمعادن',
    form: 'كبسولات',
    strength: '20 Capsules',
    manufacturer: 'Nerhadou / نرهادو',
    country: 'مصر',
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'G-105',
    standardCost: 2300,
    standardPrice: 3200,
    indications: 'كالسيوم مخلبي عالي الامتصاص للحوامل والمسنين'
  },
  {
    barcode: '6291101000125',
    name: 'فيروجلوبين ب12 كبسولات',
    nameEn: 'Feroglobin B12 Capsules',
    scientificName: 'Iron + Zinc + Folic Acid + B12',
    category: 'الفيتامينات والمكملات الغذائية والمعادن',
    form: 'كبسولات',
    strength: '30 Capsules',
    manufacturer: 'Vitabiotics / فيتابيوتكس',
    country: 'بريطانيا',
    stripsPerPackage: 2,
    piecesPerStrip: 15,
    requiresPrescription: false,
    locationRack: 'G-106',
    standardCost: 3400,
    standardPrice: 4700,
    indications: 'علاج فقر الدم ونقص الحديد دون اضطرابات هضمية'
  },
  {
    barcode: '6291101000126',
    name: 'أوميجا 3 بلس 1000 ملجم',
    nameEn: 'Omega 3 Plus 1000mg',
    scientificName: 'Fish Oil 1000mg (EPA + DHA) + Wheat Germ',
    category: 'الفيتامينات والمكملات الغذائية والمعادن',
    form: 'كبسولات',
    strength: '1000mg',
    manufacturer: 'Sedico / سيديكو',
    country: 'مصر',
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    requiresPrescription: false,
    locationRack: 'G-107',
    standardCost: 2500,
    standardPrice: 3500,
    indications: 'صحة القلب والشرايين وتنشيط الذاكرة والتركيز'
  },
  {
    barcode: '6291101000127',
    name: 'فيتامين سي فوار 1000 ملجم',
    nameEn: 'Vitamin C Effervescent 1000mg',
    scientificName: 'Ascorbic Acid 1000mg',
    category: 'الفيتامينات والمكملات الغذائية والمعادن',
    form: 'فوار',
    strength: '1000mg 20 Tab',
    manufacturer: 'Bayer / باير',
    country: 'سويسرا',
    stripsPerPackage: 1,
    piecesPerStrip: 20,
    requiresPrescription: false,
    locationRack: 'G-108',
    standardCost: 1900,
    standardPrice: 2700,
    indications: 'تقوية جهاز المناعة ومقاومة العدوى ومضاد أكسدة'
  },

  // --- أدوية الجلدية والمطهرات والمراهم ---
  {
    barcode: '6291101000140',
    name: 'بيبانثين بلس كريم',
    nameEn: 'Bepanthen Plus Cream 30g',
    scientificName: 'Dexpanthenol + Chlorhexidine',
    category: 'أدوية الجلدية والمطهرات والمراهم',
    form: 'مرهم',
    strength: '30g',
    manufacturer: 'Bayer / باير',
    country: 'ألمانيا',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: false,
    locationRack: 'H-101',
    standardCost: 2100,
    standardPrice: 2900,
    indications: 'ترميم وتطهير الجروح السطحية والحروق الخفيفة'
  },
  {
    barcode: '6291101000141',
    name: 'بيبانثين مرهم الحفاض والوردية',
    nameEn: 'Bepanthen Ointment 30g',
    scientificName: 'Dexpanthenol 5%',
    category: 'أدوية الجلدية والمطهرات والمراهم',
    form: 'مرهم',
    strength: '30g',
    manufacturer: 'Bayer / باير',
    country: 'ألمانيا',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: false,
    locationRack: 'H-102',
    standardCost: 1900,
    standardPrice: 2600,
    indications: 'علاج تسلخات الحفاض عند الرضع وتشققات الحلمة والجلد'
  },
  {
    barcode: '6291101000142',
    name: 'فيوسيدين كريم أحمر',
    nameEn: 'Fucidin Cream 2% 20g',
    scientificName: 'Fusidic Acid 2%',
    category: 'أدوية الجلدية والمطهرات والمراهم',
    form: 'مرهم',
    strength: '2% 20g',
    manufacturer: 'LEO Pharma / ليو فارما',
    country: 'الدنمارك',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: false,
    locationRack: 'H-103',
    standardCost: 2000,
    standardPrice: 2700,
    indications: 'مضاد بكتيري موضعي لعلاج الدمامل والجروح وحب الشباب'
  },
  {
    barcode: '6291101000143',
    name: 'فيوسيكورت كريم (فيوسيدين مع كورتيزون)',
    nameEn: 'Fucicort Cream 20g',
    scientificName: 'Fusidic Acid + Betamethasone',
    category: 'أدوية الجلدية والمطهرات والمراهم',
    form: 'مرهم',
    strength: '20g',
    manufacturer: 'LEO Pharma / ليو فارما',
    country: 'الدنمارك',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: false,
    locationRack: 'H-104',
    standardCost: 2500,
    standardPrice: 3400,
    indications: 'علاج الإكزيما الملتهبة والحساسية المصحوبة بعدوى'
  },
  {
    barcode: '6291101000144',
    name: 'ميبو مرهم لعلاج الحروق',
    nameEn: 'MEBO Burn Ointment 30g',
    scientificName: 'Beta-Sitosterol + Sesame Oil + Beeswax',
    category: 'أدوية الجلدية والمطهرات والمراهم',
    form: 'مرهم',
    strength: '30g',
    manufacturer: 'Julphar / جلفار الخليج',
    country: 'الإمارات',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: false,
    locationRack: 'H-105',
    standardCost: 3200,
    standardPrice: 4300,
    indications: 'تجديد خلايا الجلد وسرعة شفاء الحروق والجروح دون ندبات'
  },
  {
    barcode: '6291101000145',
    name: 'بيتاادين مطهر جروح 120 مل',
    nameEn: 'Betadine Antiseptic Solution 120ml',
    scientificName: 'Povidone Iodine 10%',
    category: 'أدوية الجلدية والمطهرات والمراهم',
    form: 'محلول',
    strength: '10% 120ml',
    manufacturer: 'Mundipharma / مونديفارما',
    country: 'سويسرا',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: false,
    locationRack: 'H-106',
    standardCost: 1500,
    standardPrice: 2100,
    indications: 'تطهير الجروح والعمليات الجراحية وقتل الجراثيم'
  },

  // --- أدوية العيون والأنف والأذن ---
  {
    barcode: '6291101000160',
    name: 'توبراكس قطرة عين',
    nameEn: 'Tobrex Eye Drops 5ml',
    scientificName: 'Tobramycin 0.3%',
    category: 'أدوية العيون والأنف والأذن',
    form: 'قطرة',
    strength: '0.3% 5ml',
    manufacturer: 'Novartis / نوفارتس',
    country: 'سويسرا',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: false,
    locationRack: 'I-101',
    standardCost: 1800,
    standardPrice: 2500,
    indications: 'مضاد حيوي لعلاج التهاب ملتحمة العين والصديد'
  },
  {
    barcode: '6291101000161',
    name: 'توبراديكس قطرة عين وأذن',
    nameEn: 'Tobradex Drops 5ml',
    scientificName: 'Tobramycin + Dexamethasone',
    category: 'أدوية العيون والأنف والأذن',
    form: 'قطرة',
    strength: '5ml',
    manufacturer: 'Novartis / نوفارتس',
    country: 'سويسرا',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: true,
    locationRack: 'I-102',
    standardCost: 2400,
    standardPrice: 3300,
    indications: 'علاج التهابات وتورم العين والأذن بعد العمليات والعدوى'
  },
  {
    barcode: '6291101000162',
    name: 'سيستان ألترا قطرة مرطبة للعين',
    nameEn: 'Systane Ultra Lubricant 10ml',
    scientificName: 'Polyethylene Glycol + Propylene Glycol',
    category: 'أدوية العيون والأنف والأذن',
    form: 'قطرة',
    strength: '10ml',
    manufacturer: 'Alcon / ألكون',
    country: 'أمريكا',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: false,
    locationRack: 'I-103',
    standardCost: 3900,
    standardPrice: 5300,
    indications: 'دموع صناعية لعلاج جفاف وحرقة وإجهاد العين والشاشات'
  },
  {
    barcode: '6291101000163',
    name: 'أوتوكالم قطرة أذن',
    nameEn: 'Otocalm Ear Drops 10ml',
    scientificName: 'Phenazone + Cinchocaine',
    category: 'أدوية العيون والأنف والأذن',
    form: 'قطرة',
    strength: '10ml',
    manufacturer: 'Sedico / سيديكو',
    country: 'مصر',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: false,
    locationRack: 'I-104',
    standardCost: 900,
    standardPrice: 1300,
    indications: 'مسكن ومخدر لآلام والتهابات الأذن الوسطى'
  },

  // --- المحاليل الوريدية وأدوية الطوارئ ---
  {
    barcode: '6291101000180',
    name: 'محلول ملحي نورمال سلاين 0.9% 500 مل',
    nameEn: 'Normal Saline 0.9% 500ml IV',
    scientificName: 'Sodium Chloride 0.9% IV Infusion',
    category: 'المحاليل الوريدية وأدوية الطوارئ',
    form: 'محلول وريدي',
    strength: '0.9% 500ml',
    manufacturer: 'Yemen Pharma / اليمن لصناعة الأدوية',
    country: 'اليمن',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: true,
    locationRack: 'J-101',
    standardCost: 600,
    standardPrice: 900,
    indications: 'تعويض الجفاف وهبوط الضغط وحامل للأدوية الوريدية'
  },
  {
    barcode: '6291101000181',
    name: 'محلول رينجر لاكتات 500 مل',
    nameEn: 'Ringer Lactate 500ml IV',
    scientificName: 'Sodium + Potassium + Calcium + Lactate',
    category: 'المحاليل الوريدية وأدوية الطوارئ',
    form: 'محلول وريدي',
    strength: '500ml',
    manufacturer: 'Yemen Pharma / اليمن لصناعة الأدوية',
    country: 'اليمن',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: true,
    locationRack: 'J-102',
    standardCost: 700,
    standardPrice: 1000,
    indications: 'تعويض شوارد وسوائل الجسم في حالات الصدمة والنزيف'
  },
  {
    barcode: '6291101000182',
    name: 'محلول ديكستروز 5% 500 مل',
    nameEn: 'Dextrose 5% 500ml IV',
    scientificName: 'Glucose 5% IV Infusion',
    category: 'المحاليل الوريدية وأدوية الطوارئ',
    form: 'محلول وريدي',
    strength: '5% 500ml',
    manufacturer: 'Modern Pharma / الحديثة للأدوية',
    country: 'اليمن',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: true,
    locationRack: 'J-103',
    standardCost: 650,
    standardPrice: 950,
    indications: 'إمداد الجسم بالطاقة وسكر الجلوكوز لمرضى الطوارئ'
  },
  {
    barcode: '6291101000183',
    name: 'أمبولات هيدروكورتيزون 100 ملجم',
    nameEn: 'Hydrocortisone 100mg Vial',
    scientificName: 'Hydrocortisone Sodium Succinate 100mg',
    category: 'المحاليل الوريدية وأدوية الطوارئ',
    form: 'حقن',
    strength: '100mg IV/IM',
    manufacturer: 'Pfizer / فايزر',
    country: 'أمريكا',
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    requiresPrescription: true,
    locationRack: 'J-104',
    standardCost: 1500,
    standardPrice: 2100,
    indications: 'علاج طوارئ الصدمة التحسسية والربو الحاد وهبوط الضغط'
  },
  {
    barcode: '6291101000184',
    name: 'ديكساميثازون 8 ملجم حقن',
    nameEn: 'Dexamethasone 8mg/2ml Ampoule',
    scientificName: 'Dexamethasone Sodium Phosphate 8mg/2ml',
    category: 'المحاليل الوريدية وأدوية الطوارئ',
    form: 'حقن',
    strength: '8mg/2ml',
    manufacturer: 'Sanofi / سانوفي',
    country: 'فرنسا',
    stripsPerPackage: 1,
    piecesPerStrip: 5,
    requiresPrescription: true,
    locationRack: 'J-105',
    standardCost: 1800,
    standardPrice: 2500,
    indications: 'مضاد التهاب ستيرويدي قوي للحساسية وتورم الدماغ والصدر'
  },
  {
    barcode: '6291101000185',
    name: 'أتروبين 1 ملجم حقن',
    nameEn: 'Atropine Sulfate 1mg/1ml',
    scientificName: 'Atropine Sulfate 1mg/ml',
    category: 'المحاليل الوريدية وأدوية الطوارئ',
    form: 'حقن',
    strength: '1mg/ml',
    manufacturer: 'Amoun / آمون للأدوية',
    country: 'مصر',
    stripsPerPackage: 1,
    piecesPerStrip: 10,
    requiresPrescription: true,
    locationRack: 'J-106',
    standardCost: 1200,
    standardPrice: 1700,
    indications: 'إنعاش القلب في حالات بطء النبض الشديد والتسمم'
  }
];
