import { Product, Batch, Supplier, Customer, Expense, PharmacySettings, User } from '../types';

export const initialSettings: PharmacySettings = {
  pharmacyName: 'صيدلية النور النموذجية',
  pharmacyNameEn: 'Al-Noor Model Pharmacy',
  branchName: 'الفرع الرئيسي - شارع الجامعة',
  phone: '01-445566',
  mobile: '777123456',
  email: 'info@alnoorpharmacy.com',
  address: 'صنعاء / الرياض - تقاطع شارع الستين مع شارع الجامعة',
  website: 'www.alnoorpharmacy.com',
  taxNumber: '300987654300003',
  crNumber: '1010897654',
  licenseNumber: 'PH-2024-8890',
  currency: 'YER',
  currencySymbol: 'ر.ي',
  enableVat: false,
  vatPercentage: 0,
  nearExpiryThresholdDays: 90,
  lowStockDefaultThreshold: 5,
  enableSoundEffects: true,
  printReceiptDirectly: false,
  receiptSize: '80mm',
  receiptPaperSize: '80mm',
  receiptHeaderMessage: 'أهلاً بكم في صيدلية النور - نتمنى لكم دوام الصحة والعافية',
  receiptFooterMessage: 'نتمنى لكم دوام الصحة والعافية - شكراً لزيارتكم',
  returnPolicyText: 'الأدوية المباعة تسترجع أو تستبدل خلال 3 أيام مع إحضار الفاتورة بشرط سلامة العبوة وحفظها في ظروف ملائمة.',
  showPharmacistNameOnReceipt: true,
  allowNegativeStock: false,
  logoUrl: '',
  showLogoOnReceipt: true,
  logoPosition: 'center',
  logoSize: 'medium',
  showPhoneOnReceipt: true,
  showAddressOnReceipt: true,
  showTaxNumberOnReceipt: true,
  showCrNumberOnReceipt: false,
  showBarcodeOnReceipt: true,
  showQrCodeOnReceipt: true,
  showCustomerOnReceipt: true,
  showDoctorOnReceipt: true,
  requirePinOnDiscount: true,
  maxDiscountWithoutManager: 10,
  requirePinOnReturn: true,
  requirePinOnPriceChange: true,
  autoLockMinutes: 15,
  enableShiftTracking: true,
  barcodeScannerSettings: {
    enabled: true,
    minBarcodeLength: 3,
    maxKeyIntervalMs: 65,
    autoConvertArabicLayout: true,
    enableGS1DataMatrix: true,
    enableSoundFeedback: true,
    autoIncrementQuantity: true,
    repeatScanCooldownMs: 2500,
    scannerSuffix: 'enter',
    customPrefix: '',
    preventInputPollution: true,
  },
};

export const initialUsers: User[] = [
  {
    id: 'usr-1',
    username: 'درويش',
    name: 'درويش (المدير العام)',
    role: 'admin',
    phone: '777000111',
    email: 'darwish@pharmacy.com',
    pin: '1447',
    avatarColor: 'purple',
    shift: 'full',
    active: true,
    permissions: [
      'pos_sale',
      'pos_discount',
      'pos_return',
      'pos_price_override',
      'inventory_view',
      'inventory_edit',
      'purchases_manage',
      'customers_manage',
      'expenses_manage',
      'reports_view',
      'settings_manage',
      'users_manage',
      'backup_manage',
    ],
    lastLogin: '2025-02-27T10:00:00Z',
    createdAt: '2024-01-01',
  },
  {
    id: 'usr-2',
    username: 'pharmacist',
    name: 'د. سارة الهاشمي (صيدلانية)',
    role: 'pharmacist',
    phone: '777000222',
    email: 'sara@pharmacy.com',
    pin: '1111',
    avatarColor: 'teal',
    shift: 'morning',
    active: true,
    permissions: [
      'pos_sale',
      'pos_discount',
      'pos_return',
      'inventory_view',
      'inventory_edit',
      'purchases_manage',
      'customers_manage',
      'reports_view',
    ],
    lastLogin: '2025-02-27T08:30:00Z',
    createdAt: '2024-01-01',
  },
  {
    id: 'usr-3',
    username: 'cashier',
    name: 'علي الكبسي (كاشير)',
    role: 'cashier',
    phone: '777000333',
    email: 'ali@pharmacy.com',
    pin: '2222',
    avatarColor: 'emerald',
    shift: 'evening',
    active: true,
    permissions: ['pos_sale', 'customers_manage'],
    lastLogin: '2025-02-26T16:00:00Z',
    createdAt: '2024-01-01',
  },
  {
    id: 'usr-4',
    username: 'accountant',
    name: 'أحمد القدسي (محاسب مالي)',
    role: 'accountant',
    phone: '777000444',
    email: 'ahmed.acc@pharmacy.com',
    pin: '3333',
    avatarColor: 'indigo',
    shift: 'morning',
    active: true,
    permissions: [
      'inventory_view',
      'purchases_manage',
      'customers_manage',
      'expenses_manage',
      'reports_view',
    ],
    lastLogin: '2025-02-27T09:15:00Z',
    createdAt: '2024-01-15',
  },
];

export const initialSuppliers: Supplier[] = [
  {
    id: 'sup-1',
    name: 'الشركة العالمية للأدوية والمستلزمات',
    companyName: 'Global Pharma Distribution',
    phone: '771234567',
    email: 'orders@globalpharma.ye',
    address: 'صنعاء - الحصبة',
    currentBalance: 450000,
    notes: 'مورد رئيسي للمضادات الحيوية وأدوية الضغط والسكري',
    createdAt: '2024-01-10',
  },
  {
    id: 'sup-2',
    name: 'مؤسسة الشفاء للتوكيلات الدوائية',
    companyName: 'Al-Shifa Drug Agencies',
    phone: '773456789',
    email: 'sales@alshifa-drugs.com',
    address: 'شارع الزبيري - صنعاء',
    currentBalance: 280000,
    notes: 'وكيل حصري لمنتجات GSK ونوفارتيس ومختبرات سانوفي',
    createdAt: '2024-01-15',
  },
  {
    id: 'sup-3',
    name: 'شركة الهلال الدوائية',
    companyName: 'Crescent Pharma Ltd',
    phone: '775678901',
    email: 'info@crescentpharma.com',
    address: 'عدن - المعلا',
    currentBalance: 120000,
    notes: 'مورد أدوية الأطفال والفيتامينات ومستحضرات التجميل العلاجية',
    createdAt: '2024-02-01',
  },
  {
    id: 'sup-4',
    name: 'الشركة الدوائية الحديثة (YPHCO)',
    companyName: 'Yemen Pharma Industry',
    phone: '777890123',
    email: 'yphco@yemenpharma.com',
    address: 'صنعاء - الروضة',
    currentBalance: 0,
    notes: 'المصنع الوطني للصناعات الدوائية - توصيل مباشر',
    createdAt: '2024-02-10',
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'عميل نقدي (عام)',
    phone: '---',
    color: 'teal',
    currentBalance: 0,
    maxCreditLimit: 0,
    totalPurchases: 1850000,
    notes: 'العميل الافتراضي للمبيعات النقدية المباشرة',
    createdAt: '2024-01-01',
  },
  {
    id: 'cust-2',
    name: 'محمد عبدالله الشامي',
    phone: '777334455',
    email: 'm.shami@gmail.com',
    address: 'حي الجامعة',
    color: 'indigo',
    currentBalance: 35000,
    maxCreditLimit: 100000,
    totalPurchases: 420000,
    notes: 'مريض سكري وضغط مزمن - عميل منتظم',
    createdAt: '2024-01-20',
  },
  {
    id: 'cust-3',
    name: 'د. خالد عبدالكريم المطري',
    phone: '771998877',
    email: 'khalid.matari@clinic.ye',
    address: 'مجمع العيادات التخصصي',
    color: 'emerald',
    currentBalance: 82000,
    maxCreditLimit: 250000,
    totalPurchases: 890000,
    notes: 'يسدد نهاية كل شهر عبر تحويل بنكي',
    createdAt: '2024-02-05',
  },
  {
    id: 'cust-4',
    name: 'أم فاطمة الحيمي',
    phone: '770112233',
    address: 'شارع بغداد',
    color: 'rose',
    currentBalance: 12500,
    maxCreditLimit: 50000,
    totalPurchases: 165000,
    notes: 'حساب شهري لأدوية العائلة',
    createdAt: '2024-02-18',
  },
  {
    id: 'cust-5',
    name: 'م. وليد أحمد الأكوع',
    phone: '775544332',
    address: 'حدة - قرب جولة الرويشان',
    color: 'amber',
    currentBalance: 0,
    maxCreditLimit: 80000,
    totalPurchases: 245000,
    notes: 'حساب مسدد بانتظام',
    createdAt: '2024-03-01',
  },
  {
    id: 'cust-6',
    name: 'أ/ سميرة منصور الهتار',
    phone: '772211445',
    address: 'حي الصافية',
    color: 'purple',
    currentBalance: 45000,
    maxCreditLimit: 60000,
    totalPurchases: 190000,
    notes: 'عميلة مستمرة - أدوية شهرية',
    createdAt: '2024-03-10',
  },
  {
    id: 'cust-7',
    name: 'صيدلية النور المجاورة',
    phone: '773399112',
    address: 'شارع الستين الجنوبي',
    color: 'sky',
    currentBalance: 120000,
    maxCreditLimit: 300000,
    totalPurchases: 1450000,
    notes: 'تبادل أدوية وطلبيات جملة عاجلة',
    createdAt: '2024-03-15',
  },
  {
    id: 'cust-8',
    name: 'الحاج عثمان قاسم السنيدار',
    phone: '778844551',
    address: 'صنعاء القديمة',
    color: 'orange',
    currentBalance: 8500,
    maxCreditLimit: 40000,
    totalPurchases: 95000,
    notes: 'عميل وفي - كبار السن',
    createdAt: '2024-03-20',
  },
];

export const initialProducts: Product[] = [
  // 1. المسكنات ومضادات الالتهاب (Analgesics & Antipyretics)
  {
    id: 'med-001',
    barcode: '6291100220011',
    name: 'بنادول إكسترا (Panadol Extra)',
    scientificName: 'Paracetamol 500mg + Caffeine 65mg',
    category: 'مسكنات وخافضات حرارة',
    form: 'أقراص',
    strength: '500mg/65mg',
    manufacturer: 'GSK GlaxoSmithKline',
    country: 'بريطانيا',
    costPrice: 2200,
    price: 3000,
    stripPrice: 1500,
    piecePrice: 150,
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    minStock: 10,
    maxStock: 100,
    requiresPrescription: false,
    locationRack: 'A-101',
    description: 'مسكن قوي وفعال للصداع وآلام الجسم وخافض للحرارة',
    vatRate: 0,
    active: true,
    totalQuantity: 45,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-002',
    barcode: '6291100220028',
    name: 'أدول 500 ملجم (Adol 500mg)',
    scientificName: 'Paracetamol 500mg',
    category: 'مسكنات وخافضات حرارة',
    form: 'أقراص',
    strength: '500mg',
    manufacturer: 'Julphar (جلفار)',
    country: 'الإمارات',
    costPrice: 1200,
    price: 1800,
    stripPrice: 900,
    piecePrice: 90,
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    minStock: 15,
    requiresPrescription: false,
    locationRack: 'A-102',
    description: 'مسكن آمن وخافض للحرارة مناسب لجميع الأعمار',
    vatRate: 0,
    active: true,
    totalQuantity: 60,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-003',
    barcode: '6291100220035',
    name: 'فولتارين 50 ملجم (Voltaren 50mg)',
    scientificName: 'Diclofenac Sodium 50mg',
    category: 'مسكنات وخافضات حرارة',
    form: 'أقراص',
    strength: '50mg',
    manufacturer: 'Novartis (نوفارتس)',
    country: 'سويسرا',
    costPrice: 3500,
    price: 4800,
    stripPrice: 2400,
    piecePrice: 240,
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    minStock: 8,
    requiresPrescription: true,
    locationRack: 'A-103',
    description: 'مضاد للالتهاب ومسكن قوي لآلام المفاصل والعضلات والأسنان',
    vatRate: 0,
    active: true,
    totalQuantity: 28,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-004',
    barcode: '6291100220042',
    name: 'بروفين 400 ملجم (Brufen 400mg)',
    scientificName: 'Ibuprofen 400mg',
    category: 'مسكنات وخافضات حرارة',
    form: 'أقراص',
    strength: '400mg',
    manufacturer: 'Abbott',
    country: 'أمريكا',
    costPrice: 2100,
    price: 3000,
    stripPrice: 1000,
    piecePrice: 100,
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    minStock: 10,
    requiresPrescription: false,
    locationRack: 'A-104',
    description: 'مضاد التهاب غير ستيرويدي فعال لآلام الدورة الشهرية والأسنان والصداع',
    vatRate: 0,
    active: true,
    totalQuantity: 35,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-005',
    barcode: '6291100220059',
    name: 'كاتافلام 50 ملجم (Cataflam 50mg)',
    scientificName: 'Diclofenac Potassium 50mg',
    category: 'مسكنات وخافضات حرارة',
    form: 'أقراص',
    strength: '50mg',
    manufacturer: 'Novartis (نوفارتس)',
    country: 'سويسرا',
    costPrice: 3800,
    price: 5200,
    stripPrice: 2600,
    piecePrice: 260,
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    minStock: 10,
    requiresPrescription: false,
    locationRack: 'A-105',
    description: 'مسكن سريع المفعول لآلام الأسنان والصداع النصفي',
    vatRate: 0,
    active: true,
    totalQuantity: 18,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },

  // 2. المضادات الحيوية (Antibiotics)
  {
    id: 'med-006',
    barcode: '6291100220066',
    name: 'أوجمنتين 1 جم (Augmentin 1g)',
    scientificName: 'Amoxicillin 875mg + Clavulanic Acid 125mg',
    category: 'مضادات حيوية',
    form: 'أقراص',
    strength: '1g (1000mg)',
    manufacturer: 'GSK GlaxoSmithKline',
    country: 'بريطانيا',
    costPrice: 5800,
    price: 7800,
    stripPrice: 3900,
    piecePrice: 550,
    stripsPerPackage: 2,
    piecesPerStrip: 7,
    minStock: 12,
    requiresPrescription: true,
    locationRack: 'B-201',
    description: 'مضاد حيوي واسع المجال لعلاج التهابات الجهاز التنفسي والمسالك والجلد',
    vatRate: 0,
    active: true,
    totalQuantity: 40,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-007',
    barcode: '6291100220073',
    name: 'زيثروماكس 500 ملجم (Zithromax 500mg)',
    scientificName: 'Azithromycin 500mg',
    category: 'مضادات حيوية',
    form: 'كبسولات',
    strength: '500mg',
    manufacturer: 'Pfizer (فايزر)',
    country: 'أمريكا',
    costPrice: 4200,
    price: 5800,
    stripPrice: 5800,
    piecePrice: 1950,
    stripsPerPackage: 1,
    piecesPerStrip: 3,
    minStock: 8,
    requiresPrescription: true,
    locationRack: 'B-202',
    description: 'كورس مضاد حيوي سريع 3 أيام لالتهابات الحلق والشعب الهوائية',
    vatRate: 0,
    active: true,
    totalQuantity: 22,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-008',
    barcode: '6291100220080',
    name: 'سيبروباي 500 ملجم (Ciprobay 500mg)',
    scientificName: 'Ciprofloxacin 500mg',
    category: 'مضادات حيوية',
    form: 'أقراص',
    strength: '500mg',
    manufacturer: 'Bayer (باير)',
    country: 'ألمانيا',
    costPrice: 3900,
    price: 5400,
    stripPrice: 2700,
    piecePrice: 270,
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    minStock: 6,
    requiresPrescription: true,
    locationRack: 'B-203',
    description: 'مضاد حيوي قوي لالتهابات المسالك البولية والنزلات المعوية',
    vatRate: 0,
    active: true,
    totalQuantity: 15,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-009',
    barcode: '6291100220097',
    name: 'سيفاكسون 1 جم حقن (Ceftriaxone 1g Vial)',
    scientificName: 'Ceftriaxone Sodium 1g IM/IV',
    category: 'مضادات حيوية',
    form: 'حقن',
    strength: '1g',
    manufacturer: 'Hikma Pharmaceuticals (حكمة)',
    country: 'الأردن',
    costPrice: 2400,
    price: 3500,
    stripPrice: 3500,
    piecePrice: 3500,
    stripsPerPackage: 1,
    piecesPerStrip: 1,
    minStock: 15,
    requiresPrescription: true,
    locationRack: 'B-204',
    description: 'حقنة مضاد حيوي وريدي/عضلي قوية للعدوى الشديدة والتنفسية',
    vatRate: 0,
    active: true,
    totalQuantity: 50,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },

  // 3. أدوية الجهاز الهضمي والمعدة (Gastrointestinal)
  {
    id: 'med-010',
    barcode: '6291100220103',
    name: 'نيكسيوم 40 ملجم (Nexium 40mg)',
    scientificName: 'Esomeprazole 40mg',
    category: 'الجهاز الهضمي والمعدة',
    form: 'أقراص',
    strength: '40mg',
    manufacturer: 'AstraZeneca (أسترازينيكا)',
    country: 'السويد',
    costPrice: 9500,
    price: 13000,
    stripPrice: 6500,
    piecePrice: 465,
    stripsPerPackage: 2,
    piecesPerStrip: 14,
    minStock: 8,
    requiresPrescription: false,
    locationRack: 'C-301',
    description: 'مثبط مضخة البروتون لعلاج قرحة المعدة والارتجاع المريئي والحموضة الشديدة',
    vatRate: 0,
    active: true,
    totalQuantity: 20,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-011',
    barcode: '6291100220110',
    name: 'موتيليريوم 10 ملجم (Motilium 10mg)',
    scientificName: 'Domperidone 10mg',
    category: 'الجهاز الهضمي والمعدة',
    form: 'أقراص',
    strength: '10mg',
    manufacturer: 'Janssen-Cilag',
    country: 'بلجيكا',
    costPrice: 2800,
    price: 3900,
    stripPrice: 1300,
    piecePrice: 130,
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    minStock: 10,
    requiresPrescription: false,
    locationRack: 'C-302',
    description: 'علاج الغثيان والقيء وتنظيم حركة الجهاز الهضمي والانتفاخ',
    vatRate: 0,
    active: true,
    totalQuantity: 32,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-012',
    barcode: '6291100220127',
    name: 'ديسكوفلاتيل (Disflatyl Drops)',
    scientificName: 'Simethicone 40mg/ml',
    category: 'الجهاز الهضمي والمعدة',
    form: 'قطرة',
    strength: '40mg/ml',
    manufacturer: 'Valeant',
    country: 'سويسرا',
    costPrice: 1900,
    price: 2700,
    minStock: 8,
    requiresPrescription: false,
    locationRack: 'C-303',
    description: 'طارد للغازات ومريح للمغص والانتفاخ للرضع والكبار',
    vatRate: 0,
    active: true,
    totalQuantity: 16,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-013',
    barcode: '6291100220134',
    name: 'فلاجيل 500 ملجم (Flagyl 500mg)',
    scientificName: 'Metronidazole 500mg',
    category: 'الجهاز الهضمي والمعدة',
    form: 'أقراص',
    strength: '500mg',
    manufacturer: 'Sanofi (سانوفي)',
    country: 'فرنسا',
    costPrice: 1600,
    price: 2400,
    stripPrice: 1200,
    piecePrice: 120,
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    minStock: 12,
    requiresPrescription: true,
    locationRack: 'C-304',
    description: 'مطهر معوي ومضاد للبكتيريا اللاهوائية والطفيليات والأميبا',
    vatRate: 0,
    active: true,
    totalQuantity: 42,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },

  // 4. أدوية القلب والضغط والدهون (Cardiovascular & Lipid)
  {
    id: 'med-014',
    barcode: '6291100220141',
    name: 'كونكور 5 ملجم (Concor 5mg)',
    scientificName: 'Bisoprolol Fumarate 5mg',
    category: 'القلب والضغط والدهون',
    form: 'أقراص',
    strength: '5mg',
    manufacturer: 'Merck (ميرك)',
    country: 'ألمانيا',
    costPrice: 4800,
    price: 6600,
    stripPrice: 2200,
    piecePrice: 220,
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    minStock: 10,
    requiresPrescription: true,
    locationRack: 'D-401',
    description: 'حاصر لمستقبلات بيتا لعلاج ضغط الدم وتنظيم ضربات القلب وقصور الشرايين',
    vatRate: 0,
    active: true,
    totalQuantity: 30,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-015',
    barcode: '6291100220158',
    name: 'ليبيتور 20 ملجم (Lipitor 20mg)',
    scientificName: 'Atorvastatin 20mg',
    category: 'القلب والضغط والدهون',
    form: 'أقراص',
    strength: '20mg',
    manufacturer: 'Pfizer (فايزر)',
    country: 'أمريكا',
    costPrice: 8200,
    price: 11500,
    stripPrice: 3850,
    piecePrice: 385,
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    minStock: 8,
    requiresPrescription: true,
    locationRack: 'D-402',
    description: 'مخفض قوي للكوليسترول الضار والدهون الثلاثية والوقاية من الجلطات',
    vatRate: 0,
    active: true,
    totalQuantity: 19,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-016',
    barcode: '6291100220165',
    name: 'جوسبرين 81 ملجم (Jusprin 81mg)',
    scientificName: 'Aspirin (Acetylsalicylic acid) 81mg',
    category: 'القلب والضغط والدهون',
    form: 'أقراص',
    strength: '81mg',
    manufacturer: 'Julphar (جلفار)',
    country: 'الإمارات',
    costPrice: 1500,
    price: 2200,
    stripPrice: 750,
    piecePrice: 75,
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    minStock: 15,
    requiresPrescription: false,
    locationRack: 'D-403',
    description: 'أسبرين أطفال للوقاية من تجلط الدم وحماية عضلة القلب',
    vatRate: 0,
    active: true,
    totalQuantity: 55,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },

  // 5. أدوية السكري والغدد (Diabetes & Endocrine)
  {
    id: 'med-017',
    barcode: '6291100220172',
    name: 'جلوكوفاج 1000 ملجم (Glucophage 1000mg)',
    scientificName: 'Metformin Hydrochloride 1000mg',
    category: 'السكري والغدد الصماء',
    form: 'أقراص',
    strength: '1000mg',
    manufacturer: 'Merck (ميرك)',
    country: 'فرنسا',
    costPrice: 3200,
    price: 4500,
    stripPrice: 1500,
    piecePrice: 150,
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    minStock: 15,
    requiresPrescription: true,
    locationRack: 'E-501',
    description: 'منظم السكر بالدم للنوع الثاني وتحسين حساسية الإنسولين',
    vatRate: 0,
    active: true,
    totalQuantity: 48,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-018',
    barcode: '6291100220189',
    name: 'جانوفيا 100 ملجم (Januvia 100mg)',
    scientificName: 'Sitagliptin 100mg',
    category: 'السكري والغدد الصماء',
    form: 'أقراص',
    strength: '100mg',
    manufacturer: 'MSD Merck Sharp & Dohme',
    country: 'أمريكا',
    costPrice: 16000,
    price: 21500,
    stripPrice: 7200,
    piecePrice: 720,
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    minStock: 4,
    requiresPrescription: true,
    locationRack: 'E-502',
    description: 'علاج حديث للسكري من النوع الثاني ينظم إفراز الإنسولين دون زيادة الوزن',
    vatRate: 0,
    active: true,
    totalQuantity: 12,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },

  // 6. الجهاز التنفسي والحساسية والكحة (Respiratory & Allergy)
  {
    id: 'med-019',
    barcode: '6291100220196',
    name: 'فينتولين بخاخ (Ventolin Evohaler)',
    scientificName: 'Salbutamol 100mcg/dose',
    category: 'الجهاز التنفسي والحساسية',
    form: 'بخاخ',
    strength: '100mcg (200 doses)',
    manufacturer: 'GSK GlaxoSmithKline',
    country: 'بريطانيا',
    costPrice: 3200,
    price: 4500,
    minStock: 10,
    requiresPrescription: false,
    locationRack: 'F-601',
    description: 'موسع شعب هوائية فوري لعلاج نوبات الربو وضيق التنفس الحاد',
    vatRate: 0,
    active: true,
    totalQuantity: 25,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-020',
    barcode: '6291100220202',
    name: 'زيرتك 10 ملجم (Zyrtec 10mg)',
    scientificName: 'Cetirizine Hydrochloride 10mg',
    category: 'الجهاز التنفسي والحساسية',
    form: 'أقراص',
    strength: '10mg',
    manufacturer: 'UCB Pharma',
    country: 'سويسرا',
    costPrice: 2600,
    price: 3600,
    stripPrice: 1800,
    piecePrice: 180,
    stripsPerPackage: 2,
    piecesPerStrip: 10,
    minStock: 10,
    requiresPrescription: false,
    locationRack: 'F-602',
    description: 'مضاد حساسية فعال لحساسية الأنف والرشح وحكة الجلد والأرتيكاريا',
    vatRate: 0,
    active: true,
    totalQuantity: 30,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-021',
    barcode: '6291100220219',
    name: 'أوتريفين بخاخ أنف (Otrivin 0.1% Adult)',
    scientificName: 'Xylometazoline Hydrochloride 0.1%',
    category: 'الجهاز التنفسي والحساسية',
    form: 'بخاخ',
    strength: '0.1% (10ml)',
    manufacturer: 'Novartis / GSK',
    country: 'سويسرا',
    costPrice: 1800,
    price: 2600,
    minStock: 8,
    requiresPrescription: false,
    locationRack: 'F-603',
    description: 'مضاد احتقان وانسداد الأنف والجيوب الأنفية سريع المفعول',
    vatRate: 0,
    active: true,
    totalQuantity: 24,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },

  // 7. الفيتامينات والمعادن والمكملات (Vitamins & Supplements)
  {
    id: 'med-022',
    barcode: '6291100220226',
    name: 'نيوروبيون أقراص (Neurobion Forte)',
    scientificName: 'Vitamin B1 + B6 + B12',
    category: 'فيتامينات ومكملات غذائية',
    form: 'أقراص',
    strength: 'B1 100mg + B6 200mg + B12 200mcg',
    manufacturer: 'Merck / P&G Health',
    country: 'النمسا',
    costPrice: 3400,
    price: 4800,
    stripPrice: 1600,
    piecePrice: 160,
    stripsPerPackage: 3,
    piecesPerStrip: 10,
    minStock: 10,
    requiresPrescription: false,
    locationRack: 'G-701',
    description: 'فيتامينات ب المركبة لتغذية الأعصاب وعلاج آلام وتنميل الأطراف',
    vatRate: 0,
    active: true,
    totalQuantity: 38,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-023',
    barcode: '6291100220233',
    name: 'فيتامين د3 50,000 وحدة (Vitamin D3 50000 IU)',
    scientificName: 'Cholecalciferol 50,000 IU',
    category: 'فيتامينات ومكملات غذائية',
    form: 'كبسولات',
    strength: '50000 IU',
    manufacturer: 'Julphar / Jamieson',
    country: 'كندا',
    costPrice: 6500,
    price: 9000,
    stripPrice: 4500,
    piecePrice: 1125,
    stripsPerPackage: 2,
    piecesPerStrip: 4,
    minStock: 6,
    requiresPrescription: false,
    locationRack: 'G-702',
    description: 'جرعة أسبوعية علاجية لنقص فيتامين د الحاد وصحة العظام والمناعة',
    vatRate: 0,
    active: true,
    totalQuantity: 15,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },

  // 8. أدوية الجلدية والعيون (Dermatology & Ophthalmology)
  {
    id: 'med-024',
    barcode: '6291100220240',
    name: 'فيوسيكورت كريم (Fucicort Cream 15g)',
    scientificName: 'Fusidic Acid 2% + Betamethasone 0.1%',
    category: 'جلدية وعيون',
    form: 'مرهم',
    strength: '15g',
    manufacturer: 'LEO Pharma',
    country: 'الدنمارك',
    costPrice: 2800,
    price: 3900,
    minStock: 8,
    requiresPrescription: false,
    locationRack: 'H-801',
    description: 'كريم مضاد حيوي وكورتيزون مهدئ لالتهابات الجلد والإكزيما المصحوبة ببكتيريا',
    vatRate: 0,
    active: true,
    totalQuantity: 26,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
  {
    id: 'med-025',
    barcode: '6291100220257',
    name: 'توبرادكس قطرة عين (Tobradex Eye Drops)',
    scientificName: 'Tobramycin 0.3% + Dexamethasone 0.1%',
    category: 'جلدية وعيون',
    form: 'قطرة',
    strength: '5ml',
    manufacturer: 'Alcon (ألكون)',
    country: 'أمريكا',
    costPrice: 4200,
    price: 5800,
    minStock: 6,
    requiresPrescription: true,
    locationRack: 'H-802',
    description: 'قطرة معقمة مضادة للالتهاب والعدوى البكتيرية في العين',
    vatRate: 0,
    active: true,
    totalQuantity: 14,
    createdAt: '2024-01-01',
    updatedAt: '2024-01-01',
  },
];

export const initialBatches: Batch[] = [
  {
    id: 'bat-001',
    productId: 'med-001',
    batchNumber: 'PND-2024-09',
    expiryDate: '2026-11-30',
    quantity: 30,
    costPrice: 2200,
    sellingPrice: 3000,
    supplierId: 'sup-1',
    supplierName: 'الشركة العالمية للأدوية',
    receivedDate: '2024-01-10',
    status: 'active',
  },
  {
    id: 'bat-001b',
    productId: 'med-001',
    batchNumber: 'PND-2023-04',
    expiryDate: '2026-09-15', // Near expiry for testing alert
    quantity: 15,
    costPrice: 2100,
    sellingPrice: 3000,
    supplierId: 'sup-1',
    supplierName: 'الشركة العالمية للأدوية',
    receivedDate: '2023-05-12',
    status: 'near_expiry',
    notes: 'دفعة قديمة - يرجى تصريفها أولاً (FIFO)',
  },
  {
    id: 'bat-002',
    productId: 'med-002',
    batchNumber: 'ADL-8821',
    expiryDate: '2027-04-30',
    quantity: 60,
    costPrice: 1200,
    sellingPrice: 1800,
    supplierId: 'sup-2',
    supplierName: 'مؤسسة الشفاء للتوكيلات',
    receivedDate: '2024-02-01',
    status: 'active',
  },
  {
    id: 'bat-003',
    productId: 'med-003',
    batchNumber: 'VLT-5541',
    expiryDate: '2026-12-31',
    quantity: 28,
    costPrice: 3500,
    sellingPrice: 4800,
    supplierId: 'sup-2',
    supplierName: 'مؤسسة الشفاء للتوكيلات',
    receivedDate: '2024-01-15',
    status: 'active',
  },
  {
    id: 'bat-004',
    productId: 'med-004',
    batchNumber: 'BRF-9901',
    expiryDate: '2027-02-28',
    quantity: 35,
    costPrice: 2100,
    sellingPrice: 3000,
    supplierId: 'sup-3',
    supplierName: 'شركة الهلال الدوائية',
    receivedDate: '2024-01-20',
    status: 'active',
  },
  {
    id: 'bat-005',
    productId: 'med-005',
    batchNumber: 'CTF-1102',
    expiryDate: '2026-10-31',
    quantity: 18,
    costPrice: 3800,
    sellingPrice: 5200,
    supplierId: 'sup-2',
    supplierName: 'مؤسسة الشفاء للتوكيلات',
    receivedDate: '2024-02-10',
    status: 'active',
  },
  {
    id: 'bat-006',
    productId: 'med-006',
    batchNumber: 'AUG-7721',
    expiryDate: '2026-12-15',
    quantity: 40,
    costPrice: 5800,
    sellingPrice: 7800,
    supplierId: 'sup-1',
    supplierName: 'الشركة العالمية للأدوية',
    receivedDate: '2024-01-25',
    status: 'active',
  },
  {
    id: 'bat-007',
    productId: 'med-007',
    batchNumber: 'ZTH-3310',
    expiryDate: '2027-05-30',
    quantity: 22,
    costPrice: 4200,
    sellingPrice: 5800,
    supplierId: 'sup-1',
    supplierName: 'الشركة العالمية للأدوية',
    receivedDate: '2024-02-05',
    status: 'active',
  },
  {
    id: 'bat-008',
    productId: 'med-008',
    batchNumber: 'CPB-4401',
    expiryDate: '2026-08-30',
    quantity: 15,
    costPrice: 3900,
    sellingPrice: 5400,
    supplierId: 'sup-1',
    supplierName: 'الشركة العالمية للأدوية',
    receivedDate: '2023-09-10',
    status: 'near_expiry',
  },
  {
    id: 'bat-009',
    productId: 'med-009',
    batchNumber: 'CFT-9002',
    expiryDate: '2027-01-31',
    quantity: 50,
    costPrice: 2400,
    sellingPrice: 3500,
    supplierId: 'sup-4',
    supplierName: 'الشركة الدوائية الحديثة',
    receivedDate: '2024-02-15',
    status: 'active',
  },
  {
    id: 'bat-010',
    productId: 'med-010',
    batchNumber: 'NXM-6020',
    expiryDate: '2027-03-31',
    quantity: 20,
    costPrice: 9500,
    sellingPrice: 13000,
    supplierId: 'sup-2',
    supplierName: 'مؤسسة الشفاء للتوكيلات',
    receivedDate: '2024-01-18',
    status: 'active',
  },
  {
    id: 'bat-011',
    productId: 'med-011',
    batchNumber: 'MTL-1120',
    expiryDate: '2027-06-30',
    quantity: 32,
    costPrice: 2800,
    sellingPrice: 3900,
    supplierId: 'sup-2',
    supplierName: 'مؤسسة الشفاء للتوكيلات',
    receivedDate: '2024-02-02',
    status: 'active',
  },
  {
    id: 'bat-012',
    productId: 'med-012',
    batchNumber: 'DSF-5501',
    expiryDate: '2027-08-31',
    quantity: 16,
    costPrice: 1900,
    sellingPrice: 2700,
    supplierId: 'sup-3',
    supplierName: 'شركة الهلال الدوائية',
    receivedDate: '2024-02-12',
    status: 'active',
  },
  {
    id: 'bat-013',
    productId: 'med-013',
    batchNumber: 'FLG-8090',
    expiryDate: '2027-04-30',
    quantity: 42,
    costPrice: 1600,
    sellingPrice: 2400,
    supplierId: 'sup-2',
    supplierName: 'مؤسسة الشفاء للتوكيلات',
    receivedDate: '2024-01-30',
    status: 'active',
  },
  {
    id: 'bat-014',
    productId: 'med-014',
    batchNumber: 'CNC-2201',
    expiryDate: '2027-07-31',
    quantity: 30,
    costPrice: 4800,
    sellingPrice: 6600,
    supplierId: 'sup-1',
    supplierName: 'الشركة العالمية للأدوية',
    receivedDate: '2024-01-12',
    status: 'active',
  },
  {
    id: 'bat-015',
    productId: 'med-015',
    batchNumber: 'LPT-9011',
    expiryDate: '2027-09-30',
    quantity: 19,
    costPrice: 8200,
    sellingPrice: 11500,
    supplierId: 'sup-1',
    supplierName: 'الشركة العالمية للأدوية',
    receivedDate: '2024-02-08',
    status: 'active',
  },
  {
    id: 'bat-016',
    productId: 'med-016',
    batchNumber: 'JSP-4411',
    expiryDate: '2027-10-31',
    quantity: 55,
    costPrice: 1500,
    sellingPrice: 2200,
    supplierId: 'sup-4',
    supplierName: 'الشركة الدوائية الحديثة',
    receivedDate: '2024-02-01',
    status: 'active',
  },
  {
    id: 'bat-017',
    productId: 'med-017',
    batchNumber: 'GLC-7701',
    expiryDate: '2027-05-31',
    quantity: 48,
    costPrice: 3200,
    sellingPrice: 4500,
    supplierId: 'sup-1',
    supplierName: 'الشركة العالمية للأدوية',
    receivedDate: '2024-01-15',
    status: 'active',
  },
  {
    id: 'bat-018',
    productId: 'med-018',
    batchNumber: 'JNV-1100',
    expiryDate: '2027-06-30',
    quantity: 12,
    costPrice: 16000,
    sellingPrice: 21500,
    supplierId: 'sup-1',
    supplierName: 'الشركة العالمية للأدوية',
    receivedDate: '2024-02-14',
    status: 'active',
  },
  {
    id: 'bat-019',
    productId: 'med-019',
    batchNumber: 'VNT-3301',
    expiryDate: '2027-01-31',
    quantity: 25,
    costPrice: 3200,
    sellingPrice: 4500,
    supplierId: 'sup-1',
    supplierName: 'الشركة العالمية للأدوية',
    receivedDate: '2024-01-22',
    status: 'active',
  },
  {
    id: 'bat-020',
    productId: 'med-020',
    batchNumber: 'ZYR-8812',
    expiryDate: '2027-04-30',
    quantity: 30,
    costPrice: 2600,
    sellingPrice: 3600,
    supplierId: 'sup-2',
    supplierName: 'مؤسسة الشفاء للتوكيلات',
    receivedDate: '2024-02-04',
    status: 'active',
  },
  {
    id: 'bat-021',
    productId: 'med-021',
    batchNumber: 'OTR-5511',
    expiryDate: '2027-03-31',
    quantity: 24,
    costPrice: 1800,
    sellingPrice: 2600,
    supplierId: 'sup-2',
    supplierName: 'مؤسسة الشفاء للتوكيلات',
    receivedDate: '2024-01-28',
    status: 'active',
  },
  {
    id: 'bat-022',
    productId: 'med-022',
    batchNumber: 'NRB-9022',
    expiryDate: '2027-08-31',
    quantity: 38,
    costPrice: 3400,
    sellingPrice: 4800,
    supplierId: 'sup-1',
    supplierName: 'الشركة العالمية للأدوية',
    receivedDate: '2024-02-11',
    status: 'active',
  },
  {
    id: 'bat-023',
    productId: 'med-023',
    batchNumber: 'VD3-4011',
    expiryDate: '2027-11-30',
    quantity: 15,
    costPrice: 6500,
    sellingPrice: 9000,
    supplierId: 'sup-3',
    supplierName: 'شركة الهلال الدوائية',
    receivedDate: '2024-01-20',
    status: 'active',
  },
  {
    id: 'bat-024',
    productId: 'med-024',
    batchNumber: 'FCC-3301',
    expiryDate: '2027-02-28',
    quantity: 26,
    costPrice: 2800,
    sellingPrice: 3900,
    supplierId: 'sup-3',
    supplierName: 'شركة الهلال الدوائية',
    receivedDate: '2024-01-18',
    status: 'active',
  },
  {
    id: 'bat-025',
    productId: 'med-025',
    batchNumber: 'TBR-1190',
    expiryDate: '2026-10-31',
    quantity: 14,
    costPrice: 4200,
    sellingPrice: 5800,
    supplierId: 'sup-2',
    supplierName: 'مؤسسة الشفاء للتوكيلات',
    receivedDate: '2024-02-09',
    status: 'active',
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp-1',
    title: 'إيجار مقر الصيدلية لشهر فبراير',
    category: 'rent',
    amount: 150000,
    date: '2024-02-01',
    paymentMethod: 'bank_transfer',
    paidBy: 'د. أحمد المنصوري',
    notes: 'تم التحويل لحساب المالك',
    createdAt: '2024-02-01',
  },
  {
    id: 'exp-2',
    title: 'فاتورة الكهرباء والإنترنت',
    category: 'electricity',
    amount: 28500,
    date: '2024-02-10',
    paymentMethod: 'cash',
    paidBy: 'د. أحمد المنصوري',
    notes: 'سداد نقدي',
    createdAt: '2024-02-10',
  },
  {
    id: 'exp-3',
    title: 'أكياس ومطبوعات ورق حراري للكاشير',
    category: 'supplies',
    amount: 14000,
    date: '2024-02-15',
    paymentMethod: 'cash',
    paidBy: 'علي الكبسي',
    notes: 'شراء رولات فواتير 80 مم + أكياس صيدلية مطبوعة',
    createdAt: '2024-02-15',
  },
];
